### ISSUE TITLE
Style checkboxes in all browsers to be dark enough to see on sunny day

### ISSUE THREAD

**Issue by stupiddingo** [idahofishgame/huntplanner_mapcenter#1]
Current default browser-selected style is not visible in Android Browser.

**Comment by stupiddingo** [comment]
One possibility http://fronteed.com/iCheck/

**Comment by pbond-idfg** [comment]
These are really nice.  We’ll have to chat about this when you get back.  I will need your help to implement.

**Comment by idahoboy** [comment]
If I understand correctly, also consider "Font Awesome" extension for Bootstrap?
